import React from 'react';
import Fade from 'react-reveal';
import {AiOutlineFileSearch} from 'react-icons/ai';
import {BsArrowRight, BsFileEarmarkCode} from 'react-icons/bs';
import {RiCharacterRecognitionLine} from 'react-icons/ri';

const About = () => {
  const about=`The application carries out the 
  conversion of the image to a digital form, by
  using Object detection and Hand-written text
  recognition. The Object detection model detects
  and classifies the various form widgets in the
  form. The Hand-written text recognizer converts
  the text in the form’s image into digital text
  (in ASCII format). The metadata generated by 
  these models are used to generate the digital form.`;
  return (
    <section id="about">
      <Fade duration={1000}>
        <div className="row">
          <h2>About The Product</h2>
          <p>{about}</p>
          <center className=" flow-diag row">
            <AiOutlineFileSearch size="150" />
            <BsArrowRight size="150" style={{padding: '20px'}} />
            <RiCharacterRecognitionLine size="150" />
            <BsArrowRight size="150" style={{padding: '20px'}} />
            <BsFileEarmarkCode size="150" />
          </center>
        </div>
      </Fade>
    </section>
  );
};

export default About;
